version: '3.7'
services:
  web:
    build: .
    environment:
     - VIRTUAL_HOST=wowee.com
  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
     - "80:80"
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
